[versions]
kermit = "2.0.4"
ktor = "3.0.0-beta-2"
dagger = "2.48"
kotlinx-coroutines = "1.8.1"
ksoup = "0.1.5"
kotlinx-serialization = "1.7.2"
kotlinx-datetime = "0.6.1"

[libraries]
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
koin-annotations = { module = "io.insert-koin:koin-annotations" }
koin-core = { module = "io.insert-koin:koin-core" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
