name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**/*.kt'
      - '**/*.kts'
  schedule:
    # Every month
    - cron: 0 0 1 * *

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: true

      - name: Cache CLI
        id: cache-cli
        uses: actions/cache@v4
        with:
          path: build/tasks/_cli_executableJarJvm/
          key: ${{ runner.os }}-cli

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 21
          cache: 'gradle'
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties

      - name: Build
        run: ./amper package -m cli
