name: Sync Job

on:
  workflow_call:
    inputs:
      useJvm:
        type: boolean
        default: false
        required: false
        description: "Should JVM executable be used instead of native"
      logLevel:
        type: string
        description: 'Log level'
        required: false
        default: WARN
    secrets:
      config:
        description: Config json
        required: true

env:
  LOG_LEVEL: ${{ inputs.logLevel }}

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Restore CLI [NATIVE]
        id: cache-cli-native
        if: "!inputs.useJvm"
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          path: kexe/spond-sync
          key: ${{ runner.os }}-spond-sync-cli-native
          restore-keys: |
            ${{ runner.os }}-spond-sync-cli-native-
      - name: Restore CLI [JVM]
        id: cache-cli-jvm
        if: "inputs.useJvm"
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          path: kexe/spond-sync.jar
          key: ${{ runner.os }}-spond-sync-cli-jvm
          restore-keys: |
            ${{ runner.os }}-spond-sync-cli-jvm-

      - name: Setup Java
        if: "inputs.useJvm"
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Prepare Config
        run: echo $SYNC_CONFIG > '${{ github.workspace }}/.config'
        env:
          SYNC_CONFIG: ${{ secrets.config }}

      - name: Sync Data [JVM]
        if: "inputs.useJvm"
        run: java --jar ./kexe/spond-sync.jar -- '${{ github.workspace }}/.config'
      - name: Sync Data [NATIVE]
        if: "!inputs.useJvm"
        run: ./kexe/spond-sync '${{ github.workspace }}/.config'

      - name: Cleanup config
        if: always()
        run: rm -rf '${{ github.workspace }}/.config'
