name: Sync

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: INFO
  schedule:
    - cron: '0 0 * * *'

env:
  LOG_LEVEL: ${{ github.event.inputs.logLevel }}

permissions:
  packages: read

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - uses: actions/checkout@v2.6.0
        with:
          ref: ${{ github.ref }}

      - name: Restore Gradle cache
        id: cache
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Prepare Config
        run: echo '${{ secrets.SYNC_CONFIG }}' > '${{ github.workspace }}/.config'

      - name: Sync Data
        run: ./gradlew :cli:run '${{ github.workspace }}/.config'
