name: Sync Job

on:
  workflow_call:
    inputs:
      logLevel:
        type: string
        description: 'Log level'
        required: false
        default: WARN
    secrets:
      config:
        description: Config json
        required: true

env:
  LOG_LEVEL: ${{ inputs.logLevel }}

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Restore CLI
        id: cache-cli
        uses: actions/cache@v4
        with:
          path: build/tasks/_cli_executableJarJvm/
          key: ${{ runner.os }}-cli

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Prepare Config
        run: echo $SYNC_CONFIG > '${{ github.workspace }}/.config'
        env:
          SYNC_CONFIG: ${{ secrets.config }}

      - name: Sync Data
        run: java --jar ./build/tasks/_cli_executableJarJvm/cli-jvm-executable.jar -- '${{ github.workspace }}/.config'

      - name: Cleanup config
        if: always()
        run: rm -rf '${{ github.workspace }}/.config'
