name: Sync

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: WARN
  schedule:
    # Every 3 hours
    - cron: 0 */3 * * *

concurrency:
  group: sync
  cancel-in-progress: true

jobs:
  sync:
    name: Sync
    uses: ./.github/workflows/sync-job.yml
    with:
      logLevel: ${{ inputs.logLevel }}
    secrets:
      config: ${{ secrets.SYNC_CONFIG }}
