name: Sync Manual

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        type: choice
        options:
          - Verbose
          - Debug
          - Info
          - Warning
          - Error
          - Assert
        required: false
        default: Info
      useJvm:
        type: boolean
        default: false
        required: false
        description: "Should JVM executable be used instead of native"
      timeoutMinutes:
        type: number
        description: Sync timeout in minutes.
        required: false
        default: 10

concurrency:
  group: sync-manual
  cancel-in-progress: true

jobs:
  sync:
    name: Sync
    uses: ./.github/workflows/sync-template.yml
    with:
      useJvm: ${{ inputs.useJvm == true }}
      logLevel: ${{ inputs.logLevel }}
      timeoutMinutes: ${{ fromJson(inputs.timeoutMinutes) }}
    secrets:
      config: ${{ secrets.SYNC_CONFIG }}
